kind: pipeline
name: default
type: docker

steps:
  - name: lint
    image: golang
    commands:
      - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
      - golangci-lint run
  - name: build
    image: golang
    commands:
      - go build

  - name: gitea_release
    image: plugins/gitea-release
    settings:
      title: ${DRONE_TAG} Release
      note: CHANGELOG.md
      api_key:
        from_secret: gitea_token
      base_url: https://git.neveris.one
      files: port
      checksum:
        - sha256
    when:
      event: tag
