kind: pipeline
name: default
type: docker

steps:
  - name: vet
    image: golang:alpine
    commands:
      - go vet
  - name: build
    image: golang:alpine
    commands:
      - go build

  - name: gitea_release
    image: plugins/gitea-release
    settings:
      title: ${DRONE_TAG} Release
      note: CHANGELOG.md
      api_key:
        from_secret: gitea_token
      base_url: https://git.neveris.one
      files: port
      checksum:
        - sha256
    when:
      event: tag
